name: "Hello World"
description: "Greet someone"
inputs:
  message-type:
    description: "Type of message to send, failure or success"
    required: true
    default: "success"
runs:
  using: "composite"
  steps:
    - name: Send to Slack
      run: echo "Hello ${{ inputs.message-type }}."
      shell: bash
