name: "Send Slack Message"
description: "Send a message to a Slack channel"
inputs:
  message-type:
    description: "Type of message to send"
    required: true
    type: choice
    options:
      - failure
      - success
      - start
      - watch
      - plain
  webhook:
    description: "Slack webhook URL"
    required: true
    type: string
  message:
    description: "Message to send, this can be used for success messages"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Send Start Message
      if: inputs.message-type == 'start'
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ inputs.webhook }}
        webhook-type: incoming-webhook
        payload: |
          {
              "text": "${{ inputs.message }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Deployment started on branch ${{ github.ref }} by push from * ${{ github.server_url }}/${{ github.actor }} ",
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":github-logo: See branch"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}"
                    }
                  ]
                },
                
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":github-logo: See Action logs"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":github-logo: Last commit"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
                    }
                  ]
                }
              ]
            }

    - name: Send Success Message
      if: inputs.message-type == 'success'
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ inputs.webhook }}
        webhook-type: incoming-webhook
        payload: |
          {
            "text": ":circle-success: ${{ inputs.message }}"
          }
    - name: Send Plain Message
      if: inputs.message-type == 'plain'
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ inputs.webhook }}
        webhook-type: incoming-webhook
        payload: |
          {
            "text": "${{ inputs.message }}"
          }

    - name: Send Failure Message
      if: inputs.message-type == 'failure'
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ inputs.webhook }}
        webhook-type: incoming-webhook
        payload: |
          {
            "text": ":circle-failed: ${{ inputs.message }}"
          }

    - name: Send Success Watch Message
      if: success() && inputs.message-type == 'watch'
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ inputs.webhook }}
        webhook-type: incoming-webhook
        payload: |
          {
            "text": ":circle-success: ${{ inputs.message }}, successful."
          }
    - name: Send Failure Watch Message
      if: failure() && inputs.message-type == 'watch'
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ inputs.webhook }}
        webhook-type: incoming-webhook
        payload: |
          {
            "text": ":circle-failed: ${{ inputs.message }}, Failed."
          }
